# Generated by Django 4.2 on 2024-04-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_country_user_verified_user_verified_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verified_password',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='ключ для верификации'),
        ),
    ]
