# Generated by Django 4.2.5 on 2023-10-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата создания'),
        ),
    ]
