# Generated by Django 5.0.2 on 2024-03-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания'),
        ),
    ]
