# Generated by Django 4.2.5 on 2023-09-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название категории')),
                ('description', models.TextField(verbose_name='описание категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование товара')),
                ('description', models.TextField(verbose_name='описание товара')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='product_images', verbose_name='превью')),
                ('category', models.IntegerField(verbose_name='категория')),
                ('cost', models.IntegerField(verbose_name='стоимость')),
                ('data_start', models.DateTimeField(verbose_name='дата создания')),
                ('data_change', models.DateTimeField(verbose_name='дата последнего изменения')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
