# Generated by Django 4.2.5 on 2024-03-03 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_data_change_alter_product_data_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='data_start',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='data_change',
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='категория'),
        ),
    ]
