# Generated by Django 5.0.2 on 2024-04-10 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='номер версии')),
                ('title', models.CharField(max_length=150, verbose_name='название версии')),
                ('feature', models.BooleanField(default=True, verbose_name='признак текущей версии')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='товар')),
            ],
        ),
    ]
