# Generated by Django 4.2 on 2024-05-20 11:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия')),
                ('surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='отчество')),
                ('contact_email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('comment', models.TextField(blank=True, help_text='Напишите уточняющую информацию', max_length=300, null=True, verbose_name='комментарий')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ('last_name', 'first_name', 'contact_email'),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Без темы', max_length=100, verbose_name='Тема письма')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Основное содержание')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime_mailing', models.DateTimeField(default=datetime.datetime(2024, 5, 20, 21, 19, 44, 427716), verbose_name='дата и время начала отправки рассылки')),
                ('stop_datetime_mailing', models.DateTimeField(default=datetime.datetime.now, verbose_name='дата и время окончания отправки рассылки')),
                ('mailing_period', models.CharField(choices=[('every_day', 'Ежедневно'), ('every_week', 'Еженедельно'), ('every_month', 'Ежемесячно')], default='once', max_length=25, verbose_name='периодичность рассылки')),
                ('mailing_status', models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('finished', 'Завершена')], default='created', max_length=25, verbose_name='статус выполнения рассылки')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='название рассылки')),
                ('is_active', models.BooleanField(default=True, verbose_name='активность рассылки')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('clients', models.ManyToManyField(related_name='client', to='mail.client', verbose_name='клиенты рассылки')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail.message', verbose_name='сообщение рассылки')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'permissions': [('set_deactivate', 'Can deactivate mailing'), ('view_all_mailings', 'Can view all mailing')],
            },
        ),
        migrations.CreateModel(
            name='Mail_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последней попытки')),
                ('attempt_status', models.CharField(choices=[('Success', 'Успешно'), ('No_success', 'Неуспешно')], default='Success', max_length=15, verbose_name='Статус попытки')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail.client', verbose_name='клиент рассылки')),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail.mailing', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'попытка отправки рассылки',
                'verbose_name_plural': 'попытки отправки рассылки',
            },
        ),
    ]
