# Generated by Django 4.2 on 2024-05-14 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_message_owner_alter_mailing_start_datetime_mailing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('set_deactivate', 'Can deactivate mailing'), ('view_all_mailings', 'Can view all mailing')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_datetime_mailing',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 18, 21, 16, 209741), verbose_name='дата и время начала отправки рассылки'),
        ),
    ]
