# Generated by Django 4.2 on 2024-05-17 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_alter_mailing_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='start_datetime_mailing',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 17, 19, 3, 58, 74715), verbose_name='дата и время начала отправки рассылки'),
        ),
    ]
