# Generated by Django 4.2 on 2024-05-17 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0011_alter_mailing_start_datetime_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='start_datetime_mailing',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 17, 20, 5, 55, 719975), verbose_name='дата и время начала отправки рассылки'),
        ),
    ]
